version: '2.3'

# this is the basic app architecture for deployment

services:

  # gateway:
  #   restart: always
  #   image: nginx
  #   build: ./gateway
  #   volumes_from:
  #    - web-client
  #   ports:
  #    - "80:80"
  #    - "443:443"
  #   depends_on:
  #    - users-api
  #    - location-api
  #    - privileged-api
  #    - web-client

  users-api:
    restart: always
    build: ./users-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_api_db
      POSTGRES_HOST: users-db
      POSTGRES_PORT: 5432
    ports:
     - "5048:5000"
    depends_on:
     - users-db

  location-api:
    restart: always
    build: ./location-api
    ports:
     - "5042:5000"
    env_file:
     - .env
    depends_on:
     - influxdb

  privileged-api:
    restart: always
    build: ./privileged-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: privileged_api_db
      POSTGRES_HOST: privileged-db
      POSTGRES_PORT: 5432
      SECRET: secret
    volumes:
      - ./privileged-api:/usr/src/app/privileged-api
    ports:
      - "5049:5000"
    depends_on:
     - privileged-db

  users-data:
    image: postgres
    volumes:
     - /var/lib/postgresql
    command: "true"

  privileged-data:
    image: postgres
    volumes:
     - /var/lib/postgresql
    command: "true"

  location-data:
    image: influxdb:1.8
    volumes:
     - /var/lib/influxdb
    command: "true"

  users-db:
    restart: always
    build: ./users-db
    ports:
      - "5538:5432"
    volumes_from:
      - users-data
    networks:
      - default

  privileged-db:
    restart: always
    build: ./privileged-db
    ports:
      - "5539:5432"
    volumes_from:
      - privileged-data
    networks:
      - default

  influxdb:
    restart: always
    build: ./location-db
    ports:
     - "8083:8083"
     - "8086:8086"
     - "8090:8090"
    volumes_from:
     - location-data
    env_file:
     - .env

  queue:
    build: ./queue

  py-worker:
    build: ./py-worker
    restart: always
    scale: 3
    depends_on:
     - queue
    env_file:
     - .env
