version: '2.3'

# this is the basic app architecture for deployment

services:

#  gateway: :
#    restart: always
#    image: nginx
#    build: ./gateway
#    volumes_from:
#     - web-client
#    ports:
#     - "80:80"
#     - "443:443"
#    depends_on:
#     - users-api
#     - location-api
#     - privileged-api
#     - web-client

  users-api:
    restart: always
    build: ./users-api
    environment:
      POSTGRES_USER: users-api
      POSTGRES_PASSWORD: users-api-pass
      POSTGRES_DB: users-api-db
      POSTGRES_HOST: users-db
      POSTGRES_PORT: 5432
    volumes:
      - ./users-api:/usr/src/app/users-api
    ports:
      - "5000:5000"
#    expose:
#      - "5000"
    depends_on:
     - users-db

#  location-api:
#    restart: always
#    build: ./location-api
#    env_file:
#     - .env
#    depends_on:
#     - location-db
#
  privileged-api:
    restart: always
    build: ./privileged-api
    environment:
      POSTGRES_USER: privileged-api
      POSTGRES_PASSWORD: privileged-api-pass
      POSTGRES_DB: privileged-api-db
      POSTGRES_HOST: privileged-db
      POSTGRES_PORT: 5432
      SECRET: secret
    ports:
      - "5001:5000"
#    expose:
#      - "5000"
    depends_on:
     - privileged-db

#  users-data:
#    image: postgres
#    volumes:
#     - /var/lib/postgresql
#    command: "true"

#  privileged-data:
#    image: postgres
#    volumes:
#     - /var/lib/postgresql
#    command: "true"
#
#  privileged-data:
#    image: influxdb:latest
#    volumes:
#     - /var/lib/influxdb
#    command: "true"

  users-db:
    restart: always
    build: ./users-db
    environment:
      POSTGRES_USER: users-api
      POSTGRES_PASSWORD: users-api-pass
#      POSTGRES_DB: users-api-db
    volumes:
     - ./users-api-postgres-data:/var/lib/postgresql/data
    networks:
      - default

  privileged-db:
    restart: always
    build: ./privileged-db
    environment:
      POSTGRES_USER: privileged-api
      POSTGRES_PASSWORD: privileged-api-pass
#      POSTGRES_DB: privileged-api-db
    volumes:
      - ./privileged-api-postgres-data:/var/lib/postgresql/data
    networks:
      - default

#  location-db:
#    restart: always
#    build: ./location-db
#    ports:
#     - "8083:8083"
#     - "8086:8086"
#     - "8090:8090"
#    volumes_from:
#     - location-data
#    env_file:
#     - .env
  
#  web-client:
#    build: ./web-client
#    volumes:
#     - /usr/share/nginx/html
#
#  queue:
#    # TODO
#
#  worker:
#    # TODO