from app import db


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    # unique identifier generated by the mobile app and used
    # as the ID in Location API
    uuid = db.Column(db.Integer, unique=True, nullable=False)

    # healty, suspected, covid_positive, covid_negative
    # TODO: use Enum
    status = db.Column(db.String, nullable=False)

    def __init__(self, uuid, status="healthy"):
        super().__init__()
        self.status = status
        self.uuid = uuid
